import { Platform, StyleSheet } from 'react-native';

export const authFontFamily = Platform.select({
  web: '"Plus Jakarta Sans", Inter, ui-sans-serif, system-ui, sans-serif',
  ios: 'System',
  default: 'sans-serif',
});

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    alignItems: 'center',
  },
  card: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
    borderWidth: 1,
    shadowColor: '#004cca',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  title: {
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '800',
    letterSpacing: -0.4,
    fontFamily: authFontFamily,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    fontFamily: authFontFamily,
  },
  fieldGroup: {
    marginTop: 22,
  },
  label: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    marginBottom: 8,
    fontFamily: authFontFamily,
  },
  phoneField: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
  },
  textField: {
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '500',
    fontFamily: authFontFamily,
  },
  countryCode: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '600',
    fontFamily: authFontFamily,
  },
  input: {
    flex: 1,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '500',
    paddingVertical: 0,
    fontFamily: authFontFamily,
  },
  primaryButton: {
    marginTop: 18,
    minHeight: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0a6bdc',
    shadowColor: '#0a6bdc',
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  primaryButtonDisabled: {
    opacity: 0.55,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
    fontFamily: authFontFamily,
  },
  secondaryButton: {
    marginTop: 12,
    minHeight: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  secondaryButtonText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '700',
    fontFamily: authFontFamily,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 8,
    paddingVertical: 4,
    paddingRight: 8,
  },
  backButtonText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    fontFamily: authFontFamily,
  },
  footerText: {
    marginTop: 28,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    fontFamily: authFontFamily,
  },
  footerLink: {
    color: '#0a6bdc',
    fontWeight: '800',
  },
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 22,
  },
  otpBox: {
    flex: 1,
    minHeight: 48,
    maxWidth: 48,
    borderRadius: 10,
    borderWidth: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    fontFamily: authFontFamily,
  },
  resendRow: {
    marginTop: 18,
    alignItems: 'center',
  },
  resendText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
    fontFamily: authFontFamily,
  },
  resendLink: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    fontFamily: authFontFamily,
  },
});
